### ISSUE TITLE
Flip does not flip to blue 2

### ISSUE THREAD

**Issue by ddean133** [james2doyle/ki.extend.js#10]
http://jsfiddle.net/james2doyle/qsQun/

**Comment by james2doyle** [comment]
Can you describe your problem a little more?

**Comment by ddean133** [comment]
If you open this fiddle and click on the button, the front (1) is red background.  Side 2 is actually the inverse of it rather than blue background side 2
http://jsfiddle.net/james2doyle/qsQun/

**Comment by james2doyle** [comment]
So why is this is problem with Ki.extend.js?

**Comment by ddean133** [comment]
It is a separate problem.  I didn't know how to enter a new issue, but need this to work right.

**Comment by james2doyle** [comment]
So you recognize that this is _not a problem with ki.extend.js?_

**Comment by ddean133** [comment]
Absolutely.  I just need help from you on this issue and did not know how to get it.

**Comment by james2doyle** [comment]
I can't help you with these CSS issues. You should post on some other site dedicated to that topic.
