### ISSUE TITLE
attr not working?

### ISSUE THREAD

**Issue by jenstornell** [james2doyle/ki.extend.js#8]
The first one work, with vanilla JS. The last one don't work, with ki.extend.js.

```js
$( '.items .checked' ).each(function( index ) {
    href += index.getAttribute('data-slug') + ',';
    href += $(this).attr('data-slug') + ',';
});
```

**Comment by jenstornell** [comment]
When changing `$(this)` to `$(index)` it work. Should it not be `this`, like jQuery?

**Comment by james2doyle** [comment]
Hello. This would be an issue for the [main project repo](https://github.com/dciccale/ki.js). You can see how the [code works here](https://github.com/dciccale/ki.js/blob/master/ki.js#L62-L65).

**Comment by tunnckoCore** [comment]
Hm. Actually yea, it's an issue with the `ki.js`. 

@jenstornell Can be fixed if you bind this to the `a` in line 63.

```js
c.forEach.call(this, a.bind(this), b)
```

but i think it would break some things

**Comment by jenstornell** [comment]
Okay!

I also tested https://github.com/webpro/DOMtastic and it has the exact same issue. In fact they seem to work exactly the same. I did not even need to change a line of code between the two. DOMtastic is as it seems larger than ki.js + ki.extend.js.

**Comment by webpro** [comment]
The "issue" here is that the array methods actually work as they should (see e.g. [Array.prototype.forEach at MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FArray%2FforEach). jQuery has the non-standard signature, putting the `index` argument first.

```js
$( '.items .checked' ).each(function( index, element, collection ) {}); // jQuery
$( '.items .checked' ).each(function( element, index, collection ) {}); // Everyone else
```

DOMtastic does have a feature to [build a jQuery-compatible](https://github.com/webpro/DOMtastic#jquery-compatibility) version, so you would get the behavior you expected.

**Comment by james2doyle** [comment]
I actually brought up this issue in the main ki.js repo [a while back](https://github.com/dciccale/ki.js/issues/12).

**Comment by webpro** [comment]
Yes I see, my apologies. Eventually I can only agree with @dciccale to stick with the ES5 signature.

**Comment by james2doyle** [comment]
Yeah I like it as well actually. It is easier to flip between vanilla js
and ki.js
